import { MeshGui } from "../entities/entities";

export const objectsMeshGui: MeshGui[] = [
  {
    name: "position",
    key: "x",
    min: -100,
    max: 100,
    step: 1,
    description: "Axis X",
  },
  {
    name: "position",
    key: "y",
    min: -100,
    max: 100,
    step: 1,
    description: "Axis Y",
  },
  {
    name: "position",
    key: "z",
    min: -100,
    max: 100,
    step: 1,
    description: "Axis Z",
  },
  {
    name: "scale",
    key: "x",
    min: 0,
    max: 10,
    step: 0.001,
    description: "Width",
  },
  {
    name: "scale",
    key: "y",
    min: 0,
    max: 10,
    step: 0.001,
    description: "Height",
  },
  {
    name: "scale",
    key: "z",
    min: 0,
    max: 10,
    step: 0.001,
    description: "Depth",
  },
  {
    name: "material",
    key: "color",
    description: "Color",
    min: 0,
    max: 0,
    step: 0,
  },
];
